In [3]:
import numpy as np

In [ ]:
#Soma de vetores
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
soma = x + y
soma

#Função soma vetores
def sum(x, y):
  x = np.random.randint(10, size=3)
  print('x=', x)
  y = np.random.randint(10, size=3)
  print('y=', y)
  eq = x+y
  return eq
sum(x, y)

x= [6 9 8]
y= [2 9 8]


array([ 8, 18, 16])

In [ ]:
#Produto escalar-vetor
x = np.array([1, 2, 3, 4])
a = float(2)
prod = np.dot(a, x)
prod

#Função produto escalar-vetor
def escVet(x, a):
  x = np.random.randint(10, size=3)
  print('x=', x)
  a = np.random.randint(0, 10)
  print('a=', a)
  prod = np.dot(a, x)
  return prod
escVet(x, a)

x= [0 5 5]
a= 9


array([ 0, 45, 45])

In [ ]:
#Produto vetor-vetor
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
mult = x * y
mult

#Função produto vetor-vetor
def vetVet(x, y):
  x = np.random.randint(10, size=3)
  print('x=', x)
  y = np.random.randint(10, size=3)
  print('y=', y)
  mult = np.inner(x, y)
  return mult
vetVet(x, y)

x= [0 3 3]
y= [4 2 4]


18

In [39]:
#Combinação linear
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 4, 5])
z = np.array([3, 4, 5, 6])
xs = [x, y, z]

a = float(2)
b = float(3)
c = float(4)
d = float(5)
cs = [a, b, c, d]

comb1 = list(map(lambda x: x * a, xs))
comb2 = list(map(lambda x: x * b, xs))
comb3 = list(map(lambda x: x * c, xs))
comb4 = list(map(lambda x: x * d, xs))
comb = comb1 + comb2 + comb3 + comb4

total = np.sum(comb)
total

588.0

In [61]:
#Matrizes
a = np.matrix('1 2; 3 4')
a[1, 1]

l = int(input('Digite o número de linhas: '))
c = int(input('Digite o número de colunas: '))
gnr = np.random.default_rng(0)
mat = gnr.integers(10, size=(l, c))
print(mat)

def buscaElemento(i, j):
  i = int(input('Digite a linha que deseja buscar: '))
  j = int(input('Digite a coluna que deseja buscar: '))
  if i <= l and j <= c:
    print(mat[i, j])
  else:
    print('Erro')

buscaElemento(i, j)

Digite o número de linhas: 3
Digite o número de colunas: 3
[[8 6 5]
 [2 3 0]
 [0 0 1]]
Digite a linha que deseja buscar: 1
Digite a coluna que deseja buscar: 1
3


In [133]:
#Produto matriz-vetor

l = int(input('Digite o número de linhas: '))
c = int(input('Digite o número de colunas: '))
gnr = np.random.default_rng(0)
mat = gnr.integers(10, size=(l, c))
vet = gnr.integers(10, size=(1, c))
print(' ')
print(mat)
print(' ')
print(vet)
print(' ')

for x in range(c):
  teste = vet[:, x] * mat[:, x]
  print(teste)

print(' ')
prod = (vet * mat[:, 0]) + (vet * mat[:, 1]) + (vet * mat[:, 2])
print(prod)

Digite o número de linhas: 3
Digite o número de colunas: 3
 
[[8 6 5]
 [2 3 0]
 [0 0 1]]
 
[[8 6 9]]
 
[64 16  0]
[36 18  0]
[45  0  9]
 
[[152  30   9]]


In [140]:
#Produto vetor-matriz

l = int(input('Digite o número de linhas: '))
c = int(input('Digite o número de colunas: '))
gnr = np.random.default_rng(0)
mat = gnr.integers(10, size=(l, c))
vet = gnr.integers(10, size=(1, c))
print(' ')
print(mat)
print(' ')
print(vet)
print(' ')

for x in range(c):
  teste = vet[:, x] * mat[x, :]
  print(teste)

print(' ')
prod = (vet[:, 0] * mat[0, :]) + (vet[:, 1] * mat[1, :]) + (vet[:, 2] * mat[2, :])
print(prod)

Digite o número de linhas: 3
Digite o número de colunas: 3
 
[[8 6 5]
 [2 3 0]
 [0 0 1]]
 
[[8 6 9]]
 
[64 48 40]
[12 18  0]
[0 0 9]
 
[76 66 49]
